[
  "L'Académie d'État d'Agriculture d'Ijevsk - 1,500,000 FCFA",
  "L'Académie d'État d'Agriculture d'Irkoutsk - 1,500,000 FCFA",
  "L'Académie d'État d'Agriculture d'Oulyanovsk P.A.Stolypin - 1,500,000 FCFA",
  "L'Académie d'État d'Agriculture d'Yakoutsk - 1,500,000 FCFA",
  "L'Académie d'État d'Agriculture de Nizhniy Novrogod - 1,500,000 FCFA",
  "L'Académie d'État d'Agriculture de Penza - 1,500,000 FCFA",
  "L'Académie d'État d'Agriculture de Perm l'académicien Pryanichnikov - 1,500,000 FCFA",
  "L'Académie d'État d'Agriculture de Samara - 1,500,000 FCFA",
  "L'Académie d'État d'Agriculture de la Bouriatie V.P.Filippov - 1,500,000 FCFA",
  "L'Académie d'État d'Agriculture du Briansk - 1,500,000 FCFA",
  "L'Académie d'État de l'économie forestière et des technologies de Voronej - 1,500,000 FCFA",
  "L'Académie d'État de la laiterie de Vologda N.V. Verechtchagin - 1,500,000 FCFA",
  "L'Académie d'État maritime d'Agriculture - 1,500,000 FCFA",
  "L'Institut d'État de l'industrie de l'alimentation de Kémérovo - 1,500,000 FCFA",
  "L'Institut d'État des Mines de Saint-Pétersbourg (l'Université Technique), 'la Faculté du pétrole et du gaz' - 1,500,000 FCFA",
  "L'Institut d'État des Mines de Saint-Pétersbourg G.V.Plehanov, (l'Université d'État) - 1,500,000 FCFA",
  "L'Institut des Mines de Vorkuta - 1,500,000 FCFA",
  "L'Université d'État de la production alimentaire de Moscou - 1,500,000 FCFA",
  "L'Université d'État des technologies et de la gestion de Moscou K.G. Razoumovskiy - 1,500,000 FCFA",
  "L'Université d'État du froid et des biotechnologies de Saint-Pétersbourg - 1,500,000 FCFA",
  "L'Université d'État technique d'Altaï, 'la Faculté de la chimie' - 1,500,000 FCFA",
  "L'Université d'État technique forestière de Saint-Pétersbourg - 1,500,000 FCFA",
  "L'Université d'État technologique de Kuban - 1,500,000 FCFA",
  "L'Université nationale minérale et les ressources matières premières 'L'Université minière' - 1,500,000 FCFA",
  "L'académie chimique et pharmaceutique de Saint-Pétersbourg - 1,500,000 FCFA",
  "L'académie d'État architecturale et artistique d'Oural - 1,500,000 FCFA",
  "L'académie d'État baltique de la flotte de pêche - 1,500,000 FCFA",
  "L'académie d'État chimique et pharmaceutique de Saint-Pétersbourg - 1,500,000 FCFA",
  "L'académie d'État classique Maymonid, 'la Faculté de médecine' - 1,500,000 FCFA",
  "L'académie d'État d'architecture et de la construction d'Ivanovo - 1,500,000 FCFA",
  "L'académie d'État d'architecture et de la construction de Rostov - 1,500,000 FCFA",
  "L'académie d'État d'ingenieur et technologique de Bryansk - 1,500,000 FCFA",
  "L'académie d'État d'économie et les services d'Oufa - 1,500,000 FCFA",
  "L'académie d'État de l'économie et le droit de Khabarovsk - 1,500,000 FCFA",
  "L'académie d'État de la construction d'équipement agricole du Rostov - 1,500,000 FCFA",
  "L'académie d'État du Nord médicale de Ossétie - 1,500,000 FCFA",
  "L'académie d'État du transport par eau de Moscou - 1,500,000 FCFA",
  "L'académie d'État du transport par eau de Volga - 1,500,000 FCFA",
  "L'académie d'État maritime F.F.Ouchakov - 1,500,000 FCFA",
  "L'académie d'État maritime S.O.Makarov - 1,500,000 FCFA",
  "L'académie d'État médicale d'Amour - 1,500,000 FCFA",
  "L'académie d'État médicale d'Astrakhan - 1,500,000 FCFA",
  "L'académie d'État médicale d'Ijevsk - 1,500,000 FCFA",
  "L'académie d'État médicale d'Ivanovo - 1,500,000 FCFA",
  "L'académie d'État médicale d'Omsk - 1,500,000 FCFA",
  "L'académie d'État médicale d'Orenbourg - 1,500,000 FCFA",
  "L'académie d'État médicale de Daghestan - 1,500,000 FCFA",
  "L'académie d'État médicale de Kirov - 1,500,000 FCFA",
  "L'académie d'État médicale de Kémérovo - 1,500,000 FCFA",
  "L'académie d'État médicale de Nizhniy Novrogod - 1,500,000 FCFA",
  "L'académie d'État médicale de Smolensk - 1,500,000 FCFA",
  "L'académie d'État médicale de Tchita - 1,500,000 FCFA",
  "L'académie d'État médicale de Tioumen - 1,500,000 FCFA",
  "L'académie d'État médicale de Tver - 1,500,000 FCFA",
  "L'académie d'État médicale de Voronej N.N.Bourdenko - 1,500,000 FCFA",
  "L'académie d'État pharmaceutique de Perm - 1,500,000 FCFA",
  "L'académie d'État pharmaceutique de Piatigorsk - 1,500,000 FCFA",
  "L'académie d'État technique d’Angarsk - 1,500,000 FCFA",
  "L'académie d'État technologique de Kirov - 1,500,000 FCFA",
  "L'académie d'État technologique de Penza - 1,500,000 FCFA",
  "L'académie d'économie et le droit d'Altaï - 1,500,000 FCFA",
  "L'académie de Novosibirsk d'État du transport par eau - 1,500,000 FCFA",
  "L'académie du marketing et des technologies sociales et informatiques - 1,500,000 FCFA",
  "L'académie financière-technologique de Moscou - 1,500,000 FCFA",
  "L'académie maritime de Sébastopol - 1,500,000 FCFA",
  "L'académie maritime de l'université d'État technique de Mourmansk - 1,500,000 FCFA",
  "L'académie militaire-médicale S.M.Kirov - 1,500,000 FCFA",
  "L'académie russe du tourisme - 1,500,000 FCFA",
  "L'académie russe du tourisme internationale - 1,500,000 FCFA",
  "L'institut chimique et technologique de Nizhnekamsk - 1,500,000 FCFA",
  "L'institut chimique et technologique de Novomoskovsk - 1,500,000 FCFA",
  "L'institut d'architecture de Moscou (l'Académie d'État) - 1,500,000 FCFA",
  "L'institut d'aviation de Moscou (l'Université Nationale scientifique) - 1,500,000 FCFA",
  "L'institut d'État de l'électronique et la mathématique de Moscou - 1,500,000 FCFA",
  "L'institut d'État des finances et l'économie de Kazan - 1,500,000 FCFA",
  "L'institut d'État du commerce et l'économie de Krasnoïarsk - 1,500,000 FCFA",
  "L'institut d'État industriel de Norilsk, 'la Faculté minière et technique' - 1,500,000 FCFA",
  "L'institut d'État métallurgique du Nord du Caucase (l'Université d'État technique) - 1,500,000 FCFA",
  "L'institut d'État pétrolier d'Almetyevsk - 1,500,000 FCFA",
  "L'institut d'État technique de Saint-Pétersbourg (l'Université technique) - 1,500,000 FCFA",
  "L'institut d'État technologique de Maikop, 'la Faculté du pétrole et du gaz' - 1,500,000 FCFA",
  "L'institut d'État technologique de Saint-Pétersbourg (l'Université Technique) - 1,500,000 FCFA",
  "L'institut d'économie et le droit d'Altaï - 1,500,000 FCFA",
  "L'institut de gaz et de pétrole de Yamal (l'université d'État de gaz et de pétrole de Tioumen) - 1,500,000 FCFA",
  "L'institut de l'acier et les alliages de Moscou - 1,500,000 FCFA",
  "L'institut de l'entreprise internationale et le management de Kuban - 1,500,000 FCFA",
  "L'institut de médecine 'Reaviz' de Samara - 1,500,000 FCFA",
  "L'institut de médecine V.M.Molotov - 1,500,000 FCFA",
  "L'institut de médecine de Chkalovsk - 1,500,000 FCFA",
  "L'institut de médecine du Ministère de la santé de la Fédération de Russie de Moscou (le Premier MGMU) - 1,500,000 FCFA",
  "L'institut des relations internationales et les études régionales sibérienne - 1,500,000 FCFA",
  "L'institut des technologies humanitaires et d'ingénieur de Kama - 1,500,000 FCFA",
  "L'institut des technologies maritimes de l'université d'État technique d'Astrakhan - 1,500,000 FCFA",
  "L'institut du business de l'industrie pétrolière et gazière de Moscou - 1,500,000 FCFA",
  "L'institut du lien et la construction de Moscou - 1,500,000 FCFA",
  "L'institut du pétrole et du gaz de Surgut (l'université d'État de gaz et de pétrole de Tioumen) - 1,500,000 FCFA",
  "L'institut du transport par eau G.Ya.Sedov - 1,500,000 FCFA",
  "L'institut d’industrie de la pêche de l'université d'État technique d'Astrakhan - 1,500,000 FCFA",
  "L'institut médical et technique de Saint-Pétersbourg - 1,500,000 FCFA",
  "L'institut médico-social de reabilitology de Moscou - 1,500,000 FCFA",
  "L'institut physique d'ingénieur de Moscou - 1,500,000 FCFA",
  "L'institut physique et technique de Moscou - 1,500,000 FCFA",
  "L'institut pétrolier de Grozniy l'académicien M.D.Millionchtchikov - 1,500,000 FCFA",
  "L'institut énergétique de Moscou - 1,500,000 FCFA",
  "L'université Technologique d'État de Tambov - 1,500,000 FCFA",
  "L'université d'Extrême Orient fédérale - 1,500,000 FCFA",
  "L'université d'Extrême Orient fédérale, 'la Faculté de la chimie' - 1,500,000 FCFA",
  "L'université d'Extrême Orient fédérale, 'la Faculté de la géologie, la géophysique et la géoécologie' - 1,500,000 FCFA",
  "L'université d'Extrême Orient fédérale, l'Institut du pétrole et du gaz - 1,500,000 FCFA",
  "L'université d'Oulyanovsk d'État - 1,500,000 FCFA",
  "L'université d'Oural d'État - 1,500,000 FCFA",
  "L'université d'État agraire Mitchourin - 1,500,000 FCFA",
  "L'université d'État agraire d'Altaï - 1,500,000 FCFA",
  "L'université d'État agraire d'Extrême Orient - 1,500,000 FCFA",
  "L'université d'État agraire d'Omsk - 1,500,000 FCFA",
  "L'université d'État agraire d'Orenbourg - 1,500,000 FCFA",
  "L'université d'État agraire de Kazan - 1,500,000 FCFA",
  "L'université d'État agraire de Kuban - 1,500,000 FCFA",
  "L'université d'État agraire de Novosibirsk - 1,500,000 FCFA",
  "L'université d'État agraire de Saint-Pétersbourg - 1,500,000 FCFA",
  "L'université d'État agraire de Stavropol - 1,500,000 FCFA",
  "L'université d'État agraire de Volgograd - 1,500,000 FCFA",
  "L'université d'État agraire de Voronej Pierre le Grand - 1,500,000 FCFA",
  "L'université d'État agraire de la Bachkirie - 1,500,000 FCFA",
  "L'université d'État agraire du Kabardino-Balkarie V.M.Kokov - 1,500,000 FCFA",
  "L'université d'État agraire du nord d'Oural - 1,500,000 FCFA",
  "L'université d'État agrotechnologique de Riazan P.A.Kostitchev - 1,500,000 FCFA",
  "L'université d'État aérospatiale de Samara l'académicien S.P.Korolev - 1,500,000 FCFA",
  "L'université d'État aérospatiale sibérienne - 1,500,000 FCFA",
  "L'université d'État chimique et technologique d'Ivanovo - 1,500,000 FCFA",
  "L'université d'État d'Adyguée - 1,500,000 FCFA",
  "L'université d'État d'Altaï - 1,500,000 FCFA",
  "L'université d'État d'Altaï, 'la faculté chimique et technologique' - 1,500,000 FCFA",
  "L'université d'État d'Amour - 1,500,000 FCFA",
  "L'université d'État d'Astrakhan - 1,500,000 FCFA",
  "L'université d'État d'Iaroslavl P.G.Demidov - 1,500,000 FCFA",
  "L'université d'État d'Ielets I.A.Bounin - 1,500,000 FCFA",
  "L'université d'État d'Irkoutsk - 1,500,000 FCFA",
  "L'université d'État d'Irkoutsk, 'la Faculté de la géologie' - 1,500,000 FCFA",
  "L'université d'État d'Ivanovo - 1,500,000 FCFA",
  "L'université d'État d'Omsk F.M.Dostoevskiy - 1,500,000 FCFA",
  "L'université d'État d'Orenbourg, 'la Faculté de la géologie et les ressources minérales' - 1,500,000 FCFA",
  "L'université d'État d'Oulianovsk ('Faculté de médecine'), l'institut de la médecine et l'écologie d'Oulianovsk, ULGU - 1,500,000 FCFA",
  "L'université d'État d'Yugorsk, l'Institut des Mines - 1,500,000 FCFA",
  "L'université d'État d'architecture et de la construction de Kazan - 1,500,000 FCFA",
  "L'université d'État d'architecture et de la construction de Saint-Pétersbourg - 1,500,000 FCFA",
  "L'université d'État d'architecture et de la construction de Samara - 1,500,000 FCFA",
  "L'université d'État d'architecture et de la construction de Tioumen - 1,500,000 FCFA",
  "L'université d'État d'architecture et de la construction de Tomsk - 1,500,000 FCFA",
  "L'université d'État d'architecture et de la construction de Volgograd - 1,500,000 FCFA",
  "L'université d'État d'architecture et de la construction de Voronej - 1,500,000 FCFA",
  "L'université d'État d'aviation civile de Saint-Pétersbourg - 1,500,000 FCFA",
  "L'université d'État d'aviation technique d'Oufa - 1,500,000 FCFA",
  "L'université d'État d'aviation technique de Rybinsk R.A.Solov'ev - 1,500,000 FCFA",
  "L'université d'État d'ingénieur et pédagogique de Volga - 1,500,000 FCFA",
  "L'université d'État de Belgorod - 1,500,000 FCFA",
  "L'université d'État de Belgorod, 'la Faculté de médecine' - 1,500,000 FCFA",
  "L'université d'État de Belgorod, 'la faculté minière' - 1,500,000 FCFA",
  "L'université d'État de Bryansk - 1,500,000 FCFA",
  "L'université d'État de Daghestan - 1,500,000 FCFA",
  "L'université d'État de Kamtchatka Vitous Bering - 1,500,000 FCFA",
  "L'université d'État de Kazan V. I. Oul'yanov (Lénine) - 1,500,000 FCFA",
  "L'université d'État de Kazan, 'la Faculté de la chimie' - 1,500,000 FCFA",
  "L'université d'État de Khabarovsk N.P.Katanov - 1,500,000 FCFA",
  "L'université d'État de Kostroma N.A.Nekrasov - 1,500,000 FCFA",
  "L'université d'État de Koursk - 1,500,000 FCFA",
  "L'université d'État de Kuban - 1,500,000 FCFA",
  "L'université d'État de Kuban, 'la Faculté géologique' - 1,500,000 FCFA",
  "L'université d'État de Kémérovo - 1,500,000 FCFA",
  "L'université d'État de Léningrad A.S.Pouchkin - 1,500,000 FCFA",
  "L'université d'État de Moscou M.V.Lomonosov - 1,500,000 FCFA",
  "L'université d'État de Moscou M.V.Lomonosov, 'la Faculté de la chimie' - 1,500,000 FCFA",
  "L'université d'État de Moscou M.V.Lomonosov, 'la Faculté de la géologie' - 1,500,000 FCFA",
  "L'université d'État de Moscou M.V.Lomonosov, 'la Faculté de médecine' - 1,500,000 FCFA",
  "L'université d'État de Nizhniy Novrogod, 'la Faculté de la chimie' - 1,500,000 FCFA",
  "L'université d'État de Novgorod Iaroslav le Sage, 'la Faculté de médecine' - 1,500,000 FCFA",
  "L'université d'État de Novosibirsk, 'la Faculté de la chimie' - 1,500,000 FCFA",
  "L'université d'État de Novosibirsk, 'la Faculté de la géologie et la géophysique' - 1,500,000 FCFA",
  "L'université d'État de Novosibirsk, 'la Faculté de médecine' - 1,500,000 FCFA",
  "L'université d'État de Penza - 1,500,000 FCFA",
  "L'université d'État de Penza, l'Institut de médecine - 1,500,000 FCFA",
  "L'université d'État de Perm - 1,500,000 FCFA",
  "L'université d'État de Perm, 'la Faculté de la chimie' - 1,500,000 FCFA",
  "L'université d'État de Perm, 'la Faculté de la géologie' - 1,500,000 FCFA",
  "L'université d'État de Pskov - 1,500,000 FCFA",
  "L'université d'État de Pushchino - 1,500,000 FCFA",
  "L'université d'État de Pétrozavodsk - 1,500,000 FCFA",
  "L'université d'État de Pétrozavodsk, 'la Faculté minière et géologique' - 1,500,000 FCFA",
  "L'université d'État de Riazan S.A.Esénin - 1,500,000 FCFA",
  "L'université d'État de Rostov - 1,500,000 FCFA",
  "L'université d'État de Rostov, 'la Faculté de la chimie' - 1,500,000 FCFA",
  "L'université d'État de Saint-Pétersbourg 'la Faculté de la chimie' - 1,500,000 FCFA",
  "L'université d'État de Saint-Pétersbourg - 1,500,000 FCFA",
  "L'université d'État de Saint-Pétersbourg, 'la Faculté géologique' - 1,500,000 FCFA",
  "L'université d'État de Saint-Pétersbourg,'la Faculté de médecine' - 1,500,000 FCFA",
  "L'université d'État de Sakhaline - 1,500,000 FCFA",
  "L'université d'État de Sakhaline, 'la Faculté du pétrole et du gaz' - 1,500,000 FCFA",
  "L'université d'État de Samara - 1,500,000 FCFA",
  "L'université d'État de Saratov, 'la Faculté de la géologie' - 1,500,000 FCFA",
  "L'université d'État de Sotchi - 1,500,000 FCFA",
  "L'université d'État de Syktyvkar - 1,500,000 FCFA",
  "L'université d'État de Tambov G.R. Derjavine - 1,500,000 FCFA",
  "L'université d'État de Tcherepovets - 1,500,000 FCFA",
  "L'université d'État de Tchéliabinsk - 1,500,000 FCFA",
  "L'université d'État de Technologie de la Volga - 1,500,000 FCFA",
  "L'université d'État de Tioumen, l'Institut chimique - 1,500,000 FCFA",
  "L'université d'État de Togliatti - 1,500,000 FCFA",
  "L'université d'État de Tomsk - 1,500,000 FCFA",
  "L'université d'État de Tomsk, 'la Faculté de la chimie' - 1,500,000 FCFA",
  "L'université d'État de Tomsk, 'la Faculté géologique' - 1,500,000 FCFA",
  "L'université d'État de Tomsk, l'Institut du pétrole et du gaz - 1,500,000 FCFA",
  "L'université d'État de Toula - 1,500,000 FCFA",
  "L'université d'État de Toula, l'Institut de l'industrie minière - 1,500,000 FCFA",
  "L'université d'État de Toula, l'Institut de médecine - 1,500,000 FCFA",
  "L'université d'État de Tuva - 1,500,000 FCFA",
  "L'université d'État de Tver - 1,500,000 FCFA",
  "L'université d'État de Viatka - 1,500,000 FCFA",
  "L'université d'État de Vladimir Alexandre Grigoriévitch, Nikolay Grigoriévitch Stoletovy - 1,500,000 FCFA",
  "L'université d'État de Volgograd - 1,500,000 FCFA",
  "L'université d'État de Voronej - 1,500,000 FCFA",
  "L'université d'État de Voronej, 'la Faculté de la géologie' - 1,500,000 FCFA",
  "L'université d'État de construction de Rostov - 1,500,000 FCFA",
  "L'université d'État de gaz et de pétrole de Tioumen - 1,500,000 FCFA",
  "L'université d'État de l'architecture et la construction de Penza - 1,500,000 FCFA",
  "L'université d'État de l'économie et le service de Vladivostok - 1,500,000 FCFA",
  "L'université d'État de l'économie et les finances de Saint-Pétersbourg - 1,500,000 FCFA",
  "L'université d'État de l'économie, la statistique et l'informatique de Moscou - 1,500,000 FCFA",
  "L'université d'État de la Bachkirie - 1,500,000 FCFA",
  "L'université d'État de la Bachkirie, 'la Faculté de la géologie et la géomorphologie' - 1,500,000 FCFA",
  "L'université d'État de la Bouriatie - 1,500,000 FCFA",
  "L'université d'État de la Bouriatie, 'la Faculté de médecine' - 1,500,000 FCFA",
  "L'université d'État de la Kalmoukie - 1,500,000 FCFA",
  "L'université d'État de la Mordovie N.P.Ogarev (Domaine Medicales) - 1,500,000 FCFA",
  "L'université d'État de la Mordovie N.P.Ogarev - 1,500,000 FCFA",
  "L'université d'État de la Oudmourtie - 1,500,000 FCFA",
  "L'université d'État de la Tchouvachie I.N.Oul'yanov - 1,500,000 FCFA",
  "L'université d'État de la Tchouvachie, 'la Faculté de médecine' - 1,500,000 FCFA",
  "L'université d'État de la Tchétchénie - 1,500,000 FCFA",
  "L'université d'État de la Tchétchénie, 'la Faculté de médecine' - 1,500,000 FCFA",
  "L'université d'État de la Transbaïkalie 'la Faculté de l'industrie minière' - 1,500,000 FCFA",
  "L'université d'État de la biotechnologie appliquée de Moscou - 1,500,000 FCFA",
  "L'université d'État de la construction d'appareils aérospatiale de Saint-Pétersbourg - 1,500,000 FCFA",
  "L'université d'État de la construction d'appareils et l'informatique de Moscou - 1,500,000 FCFA",
  "L'université d'État de la construction de Moscou - 1,500,000 FCFA",
  "L'université d'État de la flotte marine et la flotte fluviale S.O.Makarov - 1,500,000 FCFA",
  "L'université d'État de la gestion de Moscou - 1,500,000 FCFA",
  "L'université d'État de nord-est - 1,500,000 FCFA",
  "L'université d'État de nord-est, 'la Faculté de la géologie et l'industrie minière' - 1,500,000 FCFA",
  "L'université d'État des communications aquatiques de Saint-Pétersbourg - 1,500,000 FCFA",
  "L'université d'État des géosystèmes et les géotechnologies sibérienne - 1,500,000 FCFA",
  "L'université d'État des métaux non-ferreux et l'or - 1,500,000 FCFA",
  "L'université d'État des systèmes de guidage et la radio-électronique de Tomsk - 1,500,000 FCFA",
  "L'université d'État des technologies d'ingenieur de Voronej - 1,500,000 FCFA",
  "L'université d'État des technologies et la gestion de Moscou K.G.Razoumovsky - 1,500,000 FCFA",
  "L'université d'État des télécommunications de Saint-Pétersbourg M.A.Bontch-Brouevitch - 1,500,000 FCFA",
  "L'université d'État des télécommunications et l'informatique sibérienne - 1,500,000 FCFA",
  "L'université d'État du Bratsk - 1,500,000 FCFA",
  "L'université d'État du Kabardino-Balkarie K.M.Berbekov - 1,500,000 FCFA",
  "L'université d'État du Kabardino-Balkarie, 'la Faculté de médecine' - 1,500,000 FCFA",
  "L'université d'État du Kourgan - 1,500,000 FCFA",
  "L'université d'État du Magnitogorsk - 1,500,000 FCFA",
  "L'université d'État du Maikop (l'université d'État d’Adyguéens) - 1,500,000 FCFA",
  "L'université d'État du Nord d'Ossétie K.L.Khetagourov - 1,500,000 FCFA",
  "L'université d'État du Pomorsk M.V.Lomonosov - 1,500,000 FCFA",
  "L'université d'État du Sud d'Oural - 1,500,000 FCFA",
  "L'université d'État du Sud-Ouest, 'la Faculté d'industrie minière' - 1,500,000 FCFA",
  "L'université d'État du Zabaikalsk - 1,500,000 FCFA",
  "L'université d'État du commerce et l'économie de Saint-Pétersbourg - 1,500,000 FCFA",
  "L'université d'État du service de Volga - 1,500,000 FCFA",
  "L'université d'État d’Ingouchie - 1,500,000 FCFA",
  "L'université d'État d’Orel - 1,500,000 FCFA",
  "L'université d'État d’Yugorsk - 1,500,000 FCFA",
  "L'université d'État humanitaire de Moscou - 1,500,000 FCFA",
  "L'université d'État industrielle de Moscou - 1,500,000 FCFA",
  "L'université d'État industrielle sibérienne - 1,500,000 FCFA",
  "L'université d'État maritime F.F.Ouchakova, Novosibirsk - 1,500,000 FCFA",
  "L'université d'État maritime G.I.Nevel'skiy - 1,500,000 FCFA",
  "L'université d'État maritime technique de Saint-Pétersbourg - 1,500,000 FCFA",
  "L'université d'État minière d'Oural - 1,500,000 FCFA",
  "L'université d'État minière de Moscou - 1,500,000 FCFA",
  "L'université d'État mécanique de Moscou (MAMI) - 1,500,000 FCFA",
  "L'université d'État mécanique de Moscou, 'la Faculté de l'industrie minière' - 1,500,000 FCFA",
  "L'université d'État mécanique de Moscou, l'Institut de la technologie écologique et chimique - 1,500,000 FCFA",
  "L'université d'État médical et dentaire de Moscou A.I.Evdokimov - 1,500,000 FCFA",
  "L'université d'État médicale d'Altaï - 1,500,000 FCFA",
  "L'université d'État médicale d'Extrême-Orient - 1,500,000 FCFA",
  "L'université d'État médicale d'Iaroslavl - 1,500,000 FCFA",
  "L'université d'État médicale d'Irkoutsk - 1,500,000 FCFA",
  "L'université d'État médicale d'Oural (Ekaterinbourg) - 1,500,000 FCFA",
  "L'université d'État médicale de Kazan - 1,500,000 FCFA",
  "L'université d'État médicale de Koursk - 1,500,000 FCFA",
  "L'université d'État médicale de Krasnoïarsk V.F.Voyno-Yasenetsky - 1,500,000 FCFA",
  "L'université d'État médicale de Kuban - 1,500,000 FCFA",
  "L'université d'État médicale de Novosibirsk - 1,500,000 FCFA",
  "L'université d'État médicale de Riazan I.P.Pavlov - 1,500,000 FCFA",
  "L'université d'État médicale de Rostov - 1,500,000 FCFA",
  "L'université d'État médicale de Saint-Pétersbourg I.P.Pavlov - 1,500,000 FCFA",
  "L'université d'État médicale de Samara - 1,500,000 FCFA",
  "L'université d'État médicale de Saratov V.I.Razoumovsky - 1,500,000 FCFA",
  "L'université d'État médicale de Stavropol - 1,500,000 FCFA",
  "L'université d'État médicale de Vladivostok - 1,500,000 FCFA",
  "L'université d'État médicale de Volgograd - 1,500,000 FCFA",
  "L'université d'État médicale de la Bachkirie - 1,500,000 FCFA",
  "L'université d'État médicale de nord-ouest I.I.Metchnikov - 1,500,000 FCFA",
  "L'université d'État médicale du Pacifique - 1,500,000 FCFA",
  "L'université d'État médicale du nord, Arkhangelsk - 1,500,000 FCFA",
  "L'université d'État médicale sibérienne - 1,500,000 FCFA",
  "L'université d'État médicale sud d'Oural - 1,500,000 FCFA",
  "L'université d'État nationale scientifique de Perm - 1,500,000 FCFA",
  "L'université d'État ouverte de Moscou, l'Institut du pétrole et du gaz - 1,500,000 FCFA",
  "L'université d'État polytechnique de Saint-Pétersbourg - 1,500,000 FCFA",
  "L'université d'État polytechnique de Saint-Pétersbourg, 'la Faculté de la chimie' - 1,500,000 FCFA",
  "L'université d'État pédiatrique et médicale de Saint-Pétersbourg - 1,500,000 FCFA",
  "L'université d'État pétrolière technique d'Oufa - 1,500,000 FCFA",
  "L'université d'État radiotechnique de Riazan - 1,500,000 FCFA",
  "L'université d'État radiotechnique de Taganrog - 1,500,000 FCFA",
  "L'université d'État socio-économique de Saratov - 1,500,000 FCFA",
  "L'université d'État technique 'VOENMEH' de la Baltie D.F.Ustinov - 1,500,000 FCFA",
  "L'université d'État technique d'Altaï I.I.Polzounov - 1,500,000 FCFA",
  "L'université d'État technique d'Arkhangelsk, l'Institut du pétrole et du gaz - 1,500,000 FCFA",
  "L'université d'État technique d'Astrakhan - 1,500,000 FCFA",
  "L'université d'État technique d'Astrakhan, l'Institut du pétrole et du gaz - 1,500,000 FCFA",
  "L'université d'État technique d'Extrême Orient V.V.Kouybychev - 1,500,000 FCFA",
  "L'université d'État technique d'Iaroslavl - 1,500,000 FCFA",
  "L'université d'État technique d'Ijevsk M.T.Kalashnikov - 1,500,000 FCFA",
  "L'université d'État technique d'Irkoutsk - 1,500,000 FCFA",
  "L'université d'État technique d'Irkoutsk, 'la Faculté du pétrole et du gaz' - 1,500,000 FCFA",
  "L'université d'État technique d'Irkoutsk, l'Institut de la gestion et le traitement des ressources minérales - 1,500,000 FCFA",
  "L'université d'État technique d'Omsk, 'la Faculté du pétrole et du gaz' - 1,500,000 FCFA",
  "L'université d'État technique d'Oukhta, l'Institut de la géologie - 1,500,000 FCFA",
  "L'université d'État technique d'Oukhta, l'Institut du pétrole et du gaz - 1,500,000 FCFA",
  "L'université d'État technique d'Oulianovsk - 1,500,000 FCFA",
  "L'université d'État technique de Daghestan - 1,500,000 FCFA",
  "L'université d'État technique de Daghestan, l'Institut du pétrole et du gaz - 1,500,000 FCFA",
  "L'université d'État technique de Kaliningrad (Marines et Maritimes) - 1,500,000 FCFA",
  "L'université d'État technique de Kaliningrad - 1,500,000 FCFA",
  "L'université d'État technique de Kazan A.N.Toupolev - 1,500,000 FCFA",
  "L'université d'État technique de Koursk - 1,500,000 FCFA",
  "L'université d'État technique de Kouzbass T.F.Gorbatchev - 1,500,000 FCFA",
  "L'université d'État technique de Kouzbass, l'Institut des Mines - 1,500,000 FCFA",
  "L'université d'État technique de Krasnoïarsk (l'Université Sibérienne Fédérale) - 1,500,000 FCFA",
  "L'université d'État technique de Kuban, 'la Faculté du pétrole et du gaz' - 1,500,000 FCFA",
  "L'université d'État technique de Lipetsk, l'Institut de la métallurgie - 1,500,000 FCFA",
  "L'université d'État technique de Magnitogorsk G.I.Nosov - 1,500,000 FCFA",
  "L'université d'État technique de Magnitogorsk, l'Institut de l'industrie minière - 1,500,000 FCFA",
  "L'université d'État technique de Moscou (l'Université Nationale Scientifique) - 1,500,000 FCFA",
  "L'université d'État technique de Moscou Bauman - 1,500,000 FCFA",
  "L'université d'État technique de Moscou N.E. Baouman, 'la Faculté de la chimie' - 1,500,000 FCFA",
  "L'université d'État technique de Perm, 'la Faculté du pétrole et du gaz' - 1,500,000 FCFA",
  "L'université d'État technique de Samara - 1,500,000 FCFA",
  "L'université d'État technique de Samara, 'la Faculté du pétrole et du gaz' - 1,500,000 FCFA",
  "L'université d'État technique de Saratov Y.A.Gagarine - 1,500,000 FCFA",
  "L'université d'État technique de Tambov - 1,500,000 FCFA",
  "L'université d'État technique de Tver - 1,500,000 FCFA",
  "L'université d'État technique de Tver, 'la Faculté de la géologie appliquée, de la science des mines, d'industrie pétrolière et gazière, et de la géodésie' - 1,500,000 FCFA",
  "L'université d'État technique de Volgograd - 1,500,000 FCFA",
  "L'université d'État technique de Volgograd, 'la faculté chimique et technologique' - 1,500,000 FCFA",
  "L'université d'État technique de Vologda - 1,500,000 FCFA",
  "L'université d'État technique de Voronej - 1,500,000 FCFA",
  "L'université d'État technique de Voronej, l'Institut du pétrole et du gaz - 1,500,000 FCFA",
  "L'université d'État technique de l'aviation civile de Moscou - 1,500,000 FCFA",
  "L'université d'État technique de l'aviation civile de Moscou, 'la Faculté de la chimie' - 1,500,000 FCFA",
  "L'université d'État technique de la Volga - 1,500,000 FCFA",
  "L'université d'État technique de la radiotechnique, l'électronique et l'automatique de Moscou - 1,500,000 FCFA",
  "L'université d'État technique du Komsomol-sur-Amour - 1,500,000 FCFA",
  "L'université d'État technique du Komsomolsk-sur-Amour - 1,500,000 FCFA",
  "L'université d'État technique du Lipetsk - 1,500,000 FCFA",
  "L'université d'État technique du Nord du Caucase - 1,500,000 FCFA",
  "L'université d'État technique du Nord du Caucase, l'Institut du pétrole et du gaz - 1,500,000 FCFA",
  "L'université d'État technique du Rostov - 1,500,000 FCFA",
  "L'université d'État technique d’Orel - 1,500,000 FCFA",
  "L'université d'État technique d’Oukhta - 1,500,000 FCFA",
  "L'université d'État technique d’industrie de la pêche d'Extrême Orient - 1,500,000 FCFA",
  "L'université d'État technologique de Belgorod - 1,500,000 FCFA",
  "L'université d'État technologique de Belgorod, 'la Faculté minière' - 1,500,000 FCFA",
  "L'université d'État technologique de Kostroma - 1,500,000 FCFA",
  "L'université d'État technologique de Kouban - 1,500,000 FCFA",
  "L'université d'État technologique de Moscou 'Stankin', 'la Faculté de la chimie' - 1,500,000 FCFA",
  "L'université d'État technologique de Moscou (STANKIN) - 1,500,000 FCFA",
  "L'université d'État technologique des polymères végétaux de Saint-Pétersbourg - 1,500,000 FCFA",
  "L'université d'État technologique du Maikop - 1,500,000 FCFA",
  "L'université d'État technologique d’Est de Sibérie - 1,500,000 FCFA",
  "L'université d'État économique d'Oural - 1,500,000 FCFA",
  "L'université d'État économique de Rostov - 1,500,000 FCFA",
  "L'université d'État économique de Saint-Pétersbourg - 1,500,000 FCFA",
  "L'université d'État économique de Samara - 1,500,000 FCFA",
  "L'université d'État économique du Pacifique - 1,500,000 FCFA",
  "L'université d'État électrotechnique de Saint-Pétersbourg V.I.Oul'yanov 'LETI' - 1,500,000 FCFA",
  "L'université d'État énergétique d'Ivanovo - 1,500,000 FCFA",
  "L'université d'État énergétique de Kazan - 1,500,000 FCFA",
  "L'université d'économie, la gestion et le droit de Kazan - 1,500,000 FCFA",
  "L'université de Kazan fédérale - 1,500,000 FCFA",
  "L'université de Kazan fédérale, l'Institut de la géologie - 1,500,000 FCFA",
  "L'université de Kazan fédérale, l'Institut du pétrole et du gaz - 1,500,000 FCFA",
  "L'université de Moscou S.Ju.Vitte - 1,500,000 FCFA",
  "L'université de Moscou d'État des technologies fines chimiques M.V.Lomonosova - 1,500,000 FCFA",
  "L'université de la gestion 'Tisbi' - 1,500,000 FCFA",
  "L'université de médecine de la Volga - 1,500,000 FCFA",
  "L'université de nord-est fédérale d’Iakoutsk - 1,500,000 FCFA",
  "L'université de nord-ouest fédérale M.K.Ammosov, l'Institut des Mines - 1,500,000 FCFA",
  "L'université du Nord fédérale du Caucase - 1,500,000 FCFA",
  "L'université du Sud fédérale - 1,500,000 FCFA",
  "L'université du nord (Arctique) fédérale M.V.Lomonosov, l'Institut du pétrole et du gaz - 1,500,000 FCFA",
  "L'université du nord fédérale - 1,500,000 FCFA",
  "L'université du nord fédérale M.V.Lomonosov - 1,500,000 FCFA",
  "L'université du sud fédérale, 'la Faculté de la chimie' - 1,500,000 FCFA",
  "L'université du sud fédérale, l'Institut des sciences terrestres - 1,500,000 FCFA",
  "L'université financière et industrielle de Moscou 'Synergie' - 1,500,000 FCFA",
  "L'université financière près du président de la Fédération de Russie - 1,500,000 FCFA",
  "L'université fédérale de nord-est M.K.Ammosov, l'institut de médecine - 1,500,000 FCFA",
  "L'université nationale du Pacifique - 1,500,000 FCFA",
  "L'université nationale scientifique 'MEI', 'la Faculté de la chimie' - 1,500,000 FCFA",
  "L'université nationale scientifique des télématiques, la mécanique et l'optique de Saint-Pétersbourg - 1,500,000 FCFA",
  "L'université nationale scientifique nucléaire (MIFI), l'institut d'ingenieur et physique de Moscou - 1,500,000 FCFA",
  "L'université nationale scientifique technique de Perm - 1,500,000 FCFA",
  "L'université nationale scientifique technologique 'MISiS', 'la Faculté de la chimie' - 1,500,000 FCFA",
  "L'université nationale scientifique technologique de Moscou (MISiS) - 1,500,000 FCFA",
  "L'université nationale scientifique, l'école supérieure de l'économie de Moscou - 1,500,000 FCFA",
  "L'université polytechnique de Tomsk, l'Institut des ressources minérales - 1,500,000 FCFA",
  "L'université russe chimique et technologique D.I.Mendeleev - 1,500,000 FCFA",
  "L'université russe d'État Emmanuel Kant - 1,500,000 FCFA",
  "L'université russe d'État agraire K.A.Timiryazev - 1,500,000 FCFA",
  "L'université russe d'État agraire K.A.Timiryazev, 'la Faculté de la chimie' - 1,500,000 FCFA",
  "L'université russe d'État de la hydrométéorologie - 1,500,000 FCFA",
  "L'université russe d'État de prospection géologique - 1,500,000 FCFA",
  "L'université russe d'État des technologies d'innovation et l'entreprise - 1,500,000 FCFA",
  "L'université russe d'État des technologies innovants et l'entreprise - 1,500,000 FCFA",
  "L'université russe d'État du commerce et l'économie - 1,500,000 FCFA",
  "L'université russe d'État du pétrole et du gaz I.M.Goubkine - 1,500,000 FCFA",
  "L'université russe d'État du pétrole et le gaz I.M.Goubkin, 'la faculté de la chimie' - 1,500,000 FCFA",
  "L'université russe d'État du tourisme et le service - 1,500,000 FCFA",
  "L'université russe d'État polytechnique du sud M.I.Platov (l'institut polytechnique de Novotcherkassk), 'la Faculté de la géologie, l'industrie minière et d'industrie pétrolière et gazière' - 1,500,000 FCFA",
  "L'université russe d'État technique du Sud M.I.Platov - 1,500,000 FCFA",
  "L'université russe d'État technique du sud, l'Institut du pétrole et du gaz - 1,500,000 FCFA",
  "L'université russe d'État technologique (MATI) - 1,500,000 FCFA",
  "L'université russe de l'amitié des peuples - 1,500,000 FCFA",
  "L'université russe de la coopération - 1,500,000 FCFA",
  "L'université russe nationale scientifique médicale N.I.Pirogov - 1,500,000 FCFA",
  "L'université russe économique G.V.Plehanov - 1,500,000 FCFA",
  "L'université sibérienne fédérale - 1,500,000 FCFA",
  "L'université technique ouverte de nord-ouest - 1,500,000 FCFA",
  "L'école supérieure d'aviation civile d'Oulianovsk - 1,500,000 FCFA",
  "Les Universites de La Geologie, L'industrie Miniere Et La Metallurgie de la Russie - 1,500,000 FCFA"
]