import { University } from "lucide-react";

// Données simulées pour l'application
export const mockData = {
    countries: ["France", "Canada", "Belgique", "Suisse", "Maroc", "Sénégal", "Russie"],
    
    
    categories: {
        France: ["Université Paris-Sorbonne", "École Polytechnique", "Sciences Po Paris"],
        Canada: ["Université de Montréal", "McGill University", "Université Laval"],
        Belgique: ["Université Libre de Bruxelles", "Université de Liège", "KU Leuven"],
        Suisse: ["ETH Zurich", "Université de Genève", "EPFL"],
        Maroc: ["Université Mohammed V", "Université Hassan II", "ENSA"],
        Sénégal: ["Université Cheikh Anta Diop", "Université Gaston Berger", "ISM Dakar"],
        Russie:[
            "Les Universites Medicales de la Russie",
            "Les Universites D'ingenieur Et Techniques de la Russie",
            "Les Universites Universites D'état de la Russie",
            "Les Universites Marines Et Maritimes de la Russie",
            "Les Universites D’aviation de la Russie",
            "Les Universites D’economie de la Russie",
            "Les Universites Agricoles / Agraire de la Russie",          
            "Les Universites de la Culture Et Les Arts De La Russie",
            "Les Universites D'architecture Et De La Construction de la Russie",
            "Les Universites Chimiques Et Technologiques de la Russie",
            "Les Universites Du Sport Et La Culture Physique de la Russie",
            "Les Universites de La Geologie, L'industrie Miniere Et La Metallurgie de la Russie",
            "Les Universites Humanitaires Et Les Ecoles Normales Superieures de la Russie",
            "Les Universites Juridiques de la Russie",
            "Les Universites Petro-Gaziers de la Russie",
            "Les Universites Du Transport Et Des Voies De Communication de la Russie",
            "Les Universites De La Technologie D’alimentation de la Russie",
            "Les Universites D’industrie Forestiere Et D’industrie Du Bois de la Russie",
            "Les Universites D'état Près Le Gouvernement de la Federation de Russie"
        ]
    },
    universities: {
        "Les Universites Medicales de la Russie":[
            "L'université d'État médicale d'Altaï",
            "L'académie d'État médicale d'Amour",
            "L'académie d'État médicale d'Astrakhan",
            "L'université d'État médicale de la Bachkirie",
            "L'université d'État de Belgorod, 'la Faculté de médecine'",
            "L'université d'État de la Bouriatie, 'la Faculté de médecine'",
            "L'université d'État médicale de Vladivostok",
            "L'académie militaire-médicale S.M.Kirov",
            "L'université d'État médicale de Volgograd",
            "L'académie d'État médicale de Voronej N.N.Bourdenko",
            "L'académie d'État classique Maymonid, 'la Faculté de médecine'",
            "L'académie d'État médicale de Daghestan",
            "L'université d'État médicale d'Extrême-Orient",
            "L'académie d'État médicale d'Ivanovo",
            "L'académie d'État médicale d'Ijevsk",
            "L'université d'État médicale d'Irkoutsk",
            "L'université d'État du Kabardino-Balkarie, 'la Faculté de médecine'",
            "L'université d'État médicale de Kazan",
            "L'académie d'État médicale de Kémérovo",
            "L'académie d'État médicale de Kirov",
            "L'université d'État médicale de Krasnoïarsk V.F.Voyno-Yasenetsky",
            "L'université d'État médicale de Kuban",
            "L'université d'État médicale de Koursk",
            "L'institut de médecine V.M.Molotov",
            "L'université d'État de la Mordovie N.P.Ogarev",
            "L'université d'État médical et dentaire de Moscou A.I.Evdokimov",
            "L'université d'État de Moscou M.V.Lomonosov, 'la Faculté de médecine'",
            "L'institut médico-social de reabilitology de Moscou",
            "L'institut de médecine du Ministère de la santé de la Fédération de Russie de Moscou (le Premier MGMU)",
            "L'académie d'État médicale de Nizhniy Novrogod",
            "L'université d'État de Novgorod Iaroslav le Sage, 'la Faculté de médecine'",
            "L'université d'État médicale de Novosibirsk",
            "L'université d'État de Novosibirsk, 'la Faculté de médecine'",
            "L'académie d'État médicale d'Omsk",
            "L'académie d'État médicale d'Orenbourg",
            "L'université d'État de Penza, l'Institut de médecine",
            "La première université d'État médicale de Moscou I.M.Setchenov",
            "L'académie d'État médicale de Perm",
            "L'académie d'État pharmaceutique de Perm",
            "L'université d'État de Pétrozavodsk",
            "L'académie d'État pharmaceutique de Piatigorsk",
            "L'université russe nationale scientifique médicale N.I.Pirogov",
            "L'université russe de l'amitié des peuples",
            "L'université d'État médicale de Rostov",
            "L'université d'État médicale de Riazan I.P.Pavlov",
            "L'université d'État médicale de Samara",
            "L'institut de médecine 'Reaviz' de Samara",
            "L'académie d'État chimique et pharmaceutique de Saint-Pétersbourg",
            "L'université d'État médicale de Saint-Pétersbourg I.P.Pavlov",
            "L'université d'État pédiatrique et médicale de Saint-Pétersbourg",
            "L'université d'État de Saint-Pétersbourg,'la Faculté de médecine'",
            "L'institut médical et technique de Saint-Pétersbourg",
            "L'université d'État médicale de Saratov V.I.Razoumovsky",
            "L'université d'État médicale du nord, Arkhangelsk",
            "L'université fédérale de nord-est M.K.Ammosov, l'institut de médecine",
            "L'université d'État médicale de nord-ouest I.I.Metchnikov",
            "L'académie d'État du Nord médicale de Ossétie",
            "L'université d'État médicale sibérienne",
            "L'académie d'État médicale de Smolensk",
            "L'université d'État médicale de Stavropol",
            "L'académie d'État médicale de Tver",
            "L'université d'État médicale du Pacifique",
            "L'université d'État de Toula, l'Institut de médecine",
            "L'académie d'État médicale de Tioumen",
            "L'université d'État d'Oulianovsk ('Faculté de médecine'), l'institut de la médecine et l'écologie d'Oulianovsk, ULGU",
            "L'université d'État médicale d'Oural (Ekaterinbourg)",
            "L'université d'État de la Tchétchénie, 'la Faculté de médecine'",
            "L'académie d'État médicale de Tchita",
            "L'institut de médecine de Chkalovsk",
            "L'université d'État de la Tchouvachie, 'la Faculté de médecine'",
            "L'université d'État médicale sud d'Oural",
            "L'université d'État médicale d'Iaroslavl"
        ]
        
        
        ,
        "Les Universites D'ingenieur Et Techniques de la Russie":[
            "L'université d'État technique d'Altaï I.I.Polzounov",
            "L'académie d'État technique d’Angarsk",
            "L'université d'État technique d'Astrakhan",
            "L'université d'État technique 'VOENMEH' de la Baltie D.F.Ustinov",
            "L'université d'État technologique de Belgorod",
            "L'académie d'État d'ingenieur et technologique de Bryansk",
            "L'université d'État technique de Volgograd",
            "L'Université d'État d'ingenieur et pédagogique de Volga",
            "L'université d'État technique de Volga",
            "L'université d'État technique de Vologda",
            "L'université d'État technique de Voronej",
            "L'université d'État des technologies d'ingenieur de Voronej",
            "L'université d'État technologique d’Est de Sibérie",
            "L'université d'État technique de Daghestan",
            "L'université d'État technique d'Extrême Orient V.V.Kouybychev",
            "L'université d'État technique du Rostov",
            "L'université d'État énergétique d'Ivanovo",
            "L'université d'État technique d'Ijevsk M.T.Kalashnikov",
            "L'université d'État technique d'Irkoutsk",
            "L'université d'État technique de Kazan A.N.Toupolev",
            "L'université d'État énergétique de Kazan",
            "L'université d'État technique de Kaliningrad",
            "L'académie d'État d'ingenieur et économique de Kama",
            "L'université d'État technique de Kamtchatka",
            "L'académie d'État technologique de Karachaevo-Tcherkessie",
            "L'académie d'État technologique de Kirov",
            "L'université d'État technique du Komsomol-sur-Amour",
            "L'université d'État technologique de Kostroma",
            "L'université d'État technique de Krasnoïarsk (l'Université Sibérienne Fédérale)",
            "L'université d'État technologique de Kouban",
            "L'université d'État technique de Kouzbass T.F.Gorbatchev",
            "L'université d'État technique de Koursk",
            "L'université d'État technique du Lipetsk",
            "L'université d'État technique de Magnitogorsk G.I.Nosov",
            "L'université d'État technologique du Maikop",
            "L'université d'État industrielle de Moscou",
            "L'institut d'État de l'électronique et la mathématique de Moscou",
            "L'université d'État mécanique de Moscou (MAMI)",
            "L'université d'État technique de Moscou (l'Université Nationale Scientifique)",
            "L'université d'État technique de la radiotechnique, l'électronique et l'automatique de Moscou",
            "L'université d'État technologique de Moscou (STANKIN)",
            "L'université d'État de la construction d'appareils et l'informatique de Moscou",
            "L'université d'État de la biotechnologie appliquée de Moscou",
            "L'université d'État des technologies et la gestion de Moscou K.G.Razoumovsky",
            "L'université nationale scientifique technologique de Moscou (MISiS)",
            "L'université nationale scientifique nucléaire (MIFI), l'institut d'ingenieur et physique de Moscou",
            "L'université d'État technique d’Orel",
            "L'académie d'État technologique de Penza",
            "L'université nationale scientifique technique de Perm",
            "L'université russe d'État technologique (MATI)",
            "L'université russe d'État des technologies innovants et l'entreprise",
            "L'université d'État radiotechnique de Riazan",
            "L'université d'État technique de Samara",
            "L'université d'État polytechnique de Saint-Pétersbourg",
            "L'institut d'État technologique de Saint-Pétersbourg (l'Université Technique)",
            "L'université d'État technologique des polymères végétaux de Saint-Pétersbourg",
            "L'université d'État des télécommunications de Saint-Pétersbourg M.A.Bontch-Brouevitch",
            "L'université d'État électrotechnique de Saint-Pétersbourg V.I.Oul'yanov 'LETI'",
            "L'université nationale scientifique des télématiques, la mécanique et l'optique de Saint-Pétersbourg",
            "L'université d'État technique de Saratov Y.A.Gagarine",
            "L'université technique ouverte de nord-ouest",
            "L'université d'État technique du Nord du Caucase",
            "L'université d'État industrielle sibérienne",
            "L'université d'État des télécommunications et l'informatique sibérienne",
            "L'université d'État radiotechnique de Taganrog",
            "L'université d'État technique de Tambov",
            "L'université d'État technique de Tver",
            "L'université d'État des systèmes de guidage et la radio-électronique de Tomsk",
            "L'université d'État technique d'Oulianovsk",
            "L'université d'État technique d’Oukhta",
            "L'université russe d'État technique du Sud M.I.Platov",
            "L'université d'État technique d'Iaroslavl"
        ],

            "Les Universites Universites D'état de la Russie":[
                "L'université d'État d’Adyguéens",
                "L'université d'État d'Altaï",
                "L'université d'État d'Amour",
                "L'université d'État d'Astrakhan",
                "L'université d'État de la Bachkirie",
                "L'université d'État de Belgorod",
                "L'université d'État du Bratsk",
                "L'université d'État de Bryansk",
                "L'université d'État de la Bouriatie",
                "L'université d'État de Vladimir Alexandre Grigoriévitch, Nikolay Grigoriévitch Stoletovy",
                "L'université d'État de Volgograd",
                "L'université d'État de Volga",
                "L'université d'État de Voronej",
                "L'université d'État de Viatka",
                "L'université d'État des mines d'Altaï",
                "L'université d'État de Daghestan",
                "L'université d'Extrême Orient fédérale",
                "L'université d'État d'Ielets I.A.Bounin",
                "L'université d'État du Zabaikalsk",
                "L'université d'État d'Ivanovo",
                "L'université d'État d’Ingouchie",
                "L'université d'État d'Irkoutsk",
                "L'université d'État du Kabardino-Balkarie K.M.Berbekov",
                "L'université d'État de Kazan V. I. Oul'yanov (Lénine)",
                "L'université de Kazan fédérale",
                "L'université d'État de la Kalmoukie",
                "L'université d'État de Kamtchatka Vitous Bering",
                "L'université d'État de Kémérovo",
                "L'université d'État de Kostroma N.A.Nekrasov",
                "L'université d'État de Kuban",
                "L'université d'État du Kourgan",
                "L'université d'État de Koursk",
                "L'université d'État de Léningrad A.S.Pouchkin",
                "L'université d'État du Magnitogorsk",
                "L'université d'État du Maikop (l'université d'État d’Adyguéens)",
                "L'université d'État de la Mordovie N.P.Ogarev",
                "L'université d'État de Moscou M.V.Lomonosov",
                "L'université de Moscou S.Ju.Vitte",
                "L'université d'État d'Omsk F.M.Dostoevskiy",
                "L'université d'État d’Orel",
                "L'université d'État de Penza",
                "L'université d'État nationale scientifique de Perm",
                "L'université d'État de Perm",
                "L'université d'État de Pétrozavodsk",
                "L'université d'État du Pomorsk M.V.Lomonosov",
                "L'université d'État de Pskov",
                "L'université d'État de Pushchino",
                "L'université russe d'État Emmanuel Kant",
                "L’université russe nouvelle",
                "L'université russe de l'amitié des peuples",
                "L'université d'État de Rostov",
                "L'université d'État de Riazan S.A.Esénin",
                "L'université d'État de Samara",
                "L'université d'État de Saint-Pétersbourg",
                "L'université d'État de Sakhaline",
                "L'université du nord fédérale",
                "L'université du nord fédérale M.V.Lomonosov",
                "L'université d'État de nord-est",
                "L'université de nord-est fédérale d’Iakoutsk",
                "L'université du Nord fédérale du Caucase",
                "L'université d'État du Nord d'Ossétie K.L.Khetagourov",
                "L'université sibérienne fédérale",
                "L'université d'État de Sotchi",
                "L'université d'État de Syktyvkar",
                "L'université d'État de Tambov G.P.Derjavin",
                "L'université d'État de Tver",
                "L'université nationale du Pacifique",
                "L'université d'État de Togliatti",
                "L'université d'État de Tomsk",
                "L'université d'État de Tuva",
                "L'université d'État de Toula",
                "L'université d'État de la Oudmourtie",
                "L'université d'Oulyanovsk d'État",
                "L'université d'Oural d'État",
                "L'université d'État de Khabarovsk N.P.Katanov",
                "L'université d'État de Tchéliabinsk",
                "L'université d'État de Tcherepovets",
                "L'université d'État de la Tchétchénie",
                "L'université d'État de la Tchouvachie I.N.Oul'yanov",
                "L'université d'État d’Yugorsk",
                "L'université d'État du Sud d'Oural",
                "L'université du Sud fédérale",
                "L'université d'État d'Iaroslavl P.G.Demidov"
            ],



            "Les Universites Marines Et Maritimes de la Russie":[
                "L'académie d'État baltique de la flotte de pêche",
                "Le collège maritime de pêche de Volga et Kaspiysk",
                "L'académie d'État du transport par eau de Volga",
                "L'académie d'État maritime S.O.Makarov",
                "L'académie d'État maritime F.F.Ouchakov",
                "L'université d'État maritime F.F.Ouchakova, Novosibirsk",
                "L'université d'État de la flotte marine et la flotte fluviale S.O.Makarov",
                "L'université d'État technique d’industrie de la pêche d'Extrême Orient",
                "L'institut du transport par eau G.Ya.Sedov",
                "L'institut des technologies maritimes de l'université d'État technique d'Astrakhan",
                "L'institut d’industrie de la pêche de l'université d'État technique d'Astrakhan",
                "L'université d'État technique de Kaliningrad",
                "L'université d'État technique du Komsomolsk-sur-Amour",
                "L'académie maritime de l'université d'État technique de Mourmansk",
                "L'université d'État maritime G.I.Nevel'skiy",
                "L'académie d'État du transport par eau de Moscou",
                "L'académie de Novosibirsk d'État du transport par eau",
                "Le collège d'État maritime technique de Saint-Pétersbourg",
                "L'université d'État maritime technique de Saint-Pétersbourg",
                "L'université d'État des communications aquatiques de Saint-Pétersbourg",
                "Le collège du transport par eau de Saint-Pétersbourg",
                "Le collège d’industrie de la pêche de Saint-Pétersbourg",
                "L'académie maritime de Sébastopol"
            ],



            "Les Universites D’aviation de la Russie":[
                "L'institut d'aviation de Moscou (l'Université Nationale scientifique)",
                "L'université d'État technique de l'aviation civile de Moscou",
                "L'université d'État technique de Moscou Bauman",
                "L'université d'État d'aviation technique de Rybinsk R.A.Solov'ev",
                "L'université d'État aérospatiale de Samara l'académicien S.P.Korolev",
                "L'université d'État de la construction d'appareils aérospatiale de Saint-Pétersbourg",
                "L'université d'État d'aviation civile de Saint-Pétersbourg",
                "L'université d'État aérospatiale sibérienne",
                "Le collège d'aviation de Taganrog V.M.Petlyakov",
                "Le collège d'aviation technique de Troitsk",
                "L'école supérieure d'aviation civile d'Oulianovsk",
                "L'université d'État d'aviation technique d'Oufa"
            ],



            "Les Universites D’economie de la Russie":[
                "L'académie du marketing et des technologies sociales et informatiques",
                "L'académie d'économie et le droit d'Altaï",
                "L'institut d'économie et le droit d'Altaï",
                "L'université d'État de l'économie et le service de Vladivostok",
                "L'université d'État du service de Volga",
                "L'institut d'État des finances et l'économie de Kazan",
                "L'université d'économie, la gestion et le droit de Kazan",
                "L'institut d'État du commerce et l'économie de Krasnoïarsk",
                "L'institut de l'entreprise internationale et le management de Kuban",
                "L'académie financière-technologique de Moscou",
                "L'université d'État humanitaire de Moscou",
                "L'université d'État de la gestion de Moscou",
                "L'université d'État de l'économie, la statistique et l'informatique de Moscou",
                "L'université financière et industrielle de Moscou 'Synergie'",
                "L'université nationale scientifique, l'école supérieure de l'économie de Moscou",
                "L'académie russe du tourisme",
                "L'académie russe du tourisme internationale",
                "L'université russe d'État des technologies d'innovation et l'entreprise",
                "L'université russe d'État du commerce et l'économie",
                "L'université russe d'État du tourisme et le service",
                "L'université russe de la coopération",
                "L'université russe économique G.V.Plehanov",
                "L'université d'État économique de Rostov",
                "L'université d'État économique de Samara",
                "L'université d'État du commerce et l'économie de Saint-Pétersbourg",
                "L'université d'État de l'économie et les finances de Saint-Pétersbourg",
                "L'université d'État économique de Saint-Pétersbourg",
                "L'université d'État socio-économique de Saratov",
                "L'institut des relations internationales et les études régionales sibérienne",
                "L'université d'État économique du Pacifique",
                "L'université de la gestion 'Tisbi'",
                "L'université d'État économique d'Oural",
                "L'académie d'État d'économie et les services d'Oufa",
                "L'université financière près du président de la Fédération de Russie",
                "L'académie d'État de l'économie et le droit de Khabarovsk"
            ],


            "Les Universites Agricoles / Agraire de la Russie":[
                "L'université d'État agraire d'Altaï",
                "L'université d'État agraire de la Bachkirie",
                "L'Académie d'État d'Agriculture du Briansk",
                "L'Académie d'État d'Agriculture de la Bouriatie V.P.Filippov",
                "L'université d'État agraire d'Extrême Orient",
                "L'Académie d'État d'Agriculture d'Irkoutsk",
                "L'Académie d'État d'Agriculture d'Ijevsk",
                "L'université d'État agraire du Kabardino-Balkarie V.M.Kokov",
                "L'université d'État agraire de Kazan",
                "L'université d'État agraire de Kuban",
                "L'université d'État agraire Mitchourin",
                "L'Académie d'État d'Agriculture de Nizhniy Novrogod",
                "L'université d'État agraire de Novosibirsk",
                "L'université d'État agraire d'Omsk",
                "L'université d'État agraire d'Orenbourg",
                "L'Académie d'État d'Agriculture de Penza",
                "L'Académie d'État d'Agriculture de Perm l'académicien Pryanichnikov",
                "L'Académie d'État maritime d'Agriculture",
                "L'académie d'État de la construction d'équipement agricole du Rostov",
                "L'université russe d'État agraire K.A.Timiryazev",
                "L'université d'État agrotechnologique de Riazan P.A.Kostitchev",
                "L'université d'État agraire de Saint-Pétersbourg",
                "L'Académie d'État d'Agriculture de Samara",
                "L'université d'État agraire du nord d'Oural",
                "L'université d'État agraire de Stavropol",
                "L'Académie d'État d'Agriculture d'Oulyanovsk P.A.Stolypin",
                "L'université d'État agraire de Volgograd",
                "L'université d'État agraire de Voronej Pierre le Grand",
                "L'Académie d'État d'Agriculture d'Yakoutsk"
            ],



            "Les Universites de la Culture Et Les Arts De La Russie":[
                "L'académie d'aquarelle et les beaux arts de Moscou",
                "L'académie d'État de la culture et les arts d'Altaï",
                "L'université d'État de la culture et les arts de Belgorod",
                "L'académie d'État des peintures de Voronej",
                "L'académie d'État de la culture et les arts de Sibérie orientale",
                "L'université d'État panrusse de la cinématographie S.A.Gerasimov",
                "L'école supérieure des arts de Saint-Pétersbourg",
                "L'école supérieure théâtrale M.S.Schepkin",
                "L'institut d'État industrielle d'art de Gzhel",
                "L'académie d'État de la culture slave",
                "L'académie d'État classique Majmonid",
                "L'académie d'État des arts d'Extrême Orient",
                "L'académie d'État textile d'Ivanovo",
                "Le conservatoire d'État de Kazan (l'Académie) N.G.Jiganov",
                "L'université d'État de la culture et les arts de Kazan",
                "L'université d'État de la culture et les arts de Kémérovo",
                "L'académie d'État industrielle d'art de Moscou S.G.Stroganov",
                "Le conservatoire (L'université) de Moscou",
                "L'université d'État du design et la technologie de Moscou",
                "L'université d'État de la presse de Moscou Ivan Fedorov",
                "L'institut d'État de l'art et la culture de Perm",
                "Le conservatoire d'État de Pétrozavodsk A.K.Glazounov",
                "Le conservatoire d'État de Rostov S.V.Rakhmaninov",
                "L'institut russe de textile et de l'industrie légère",
                "L'académie d'État de la culture et les arts de Samara",
                "L'académie d'État du théâtre de Saint-Pétersbourg",
                "Le conservatoire d'État de Saint-Pétersbourg N.A.Rimsky-Korsakov",
                "L'université d'État du cinéma et la télévision de Saint-Pétersbourg",
                "L'université d'État de la technologie et le design de Saint-Pétersbourg",
                "Le conservatoire d'État de Saratov L.V.Sobinov",
                "L'académie d'État architecturale et artistique d'Oural",
                "Le conservatoire d'État d'Oural M.P.Moussorgski",
                "L'institut d'État du théâtre d'Iaroslavl"
            ],


            "Les Universites D'architecture Et De La Construction de la Russie":[
    "L'université d'État d'architecture et de la construction de Volgograd",
    "L'université d'État d'architecture et de la construction de Voronej",
    "L'académie d'État d'architecture et de la construction d'Ivanovo",
    "L'université d'État d'architecture et de la construction de Kazan",
    "L'institut d'architecture de Moscou (l'Académie d'État)",
    "L'université d'État de la construction de Moscou",
    "L'institut du lien et la construction de Moscou",
    "L'université d'État de l'architecture et la construction de Penza",
    "L'académie d'État d'architecture et de la construction de Rostov",
    "L'université d'État de construction de Rostov",
    "L'université d'État d'architecture et de la construction de Samara",
    "L'université d'État d'architecture et de la construction de Saint-Pétersbourg",
    "L'université d'État d'architecture et de la construction de Tomsk",
    "L'université d'État d'architecture et de la construction de Tioumen",
    "L'académie d'État architecturale et artistique d'Oural"
],



            "Les Universites Chimiques Et Technologiques de la Russie":[
                "L'Université d'État technique d'Altaï, 'la Faculté de la chimie'",
                "L'université d'État d'Altaï, 'la faculté chimique et technologique'",
                "L'université d'État de la Bachkirie",
                "L'université d'État technique de Volgograd, 'la faculté chimique et technologique'",
                "Le collège supérieur chimique de l'Académie des Sciences de la Russie",
                "L'université d'État des métaux non-ferreux et l'or",
                "L'université d'Extrême Orient fédérale, 'la Faculté de la chimie'",
                "L'université d'État chimique et technologique d'Ivanovo",
                "L'université d'État de Kazan, 'la Faculté de la chimie'",
                "L'université d'État mécanique de Moscou, l'Institut de la technologie écologique et chimique",
                "L'université d'État technique de l'aviation civile de Moscou, 'la Faculté de la chimie'",
                "L'université d'État technique de Moscou N.E. Baouman, 'la Faculté de la chimie'",
                "L'université d'État technologique de Moscou 'Stankin', 'la Faculté de la chimie'",
                "L'université d'État de Moscou M.V.Lomonosov, 'la Faculté de la chimie'",
                "L'université de Moscou d'État des technologies fines chimiques M.V.Lomonosova",
                "L'institut physique d'ingénieur de Moscou",
                "L'institut de l'acier et les alliages de Moscou",
                "L'institut physique et technique de Moscou",
                "L'institut énergétique de Moscou",
                "L'université nationale scientifique technologique 'MISiS', 'la Faculté de la chimie'",
                "L'université nationale scientifique 'MEI', 'la Faculté de la chimie'",
                "L'université d'État de Nizhniy Novrogod, 'la Faculté de la chimie'",
                "L'institut chimique et technologique de Nizhnekamsk",
                "L'institut chimique et technologique de Novomoskovsk",
                "L'université d'État de Novosibirsk, 'la Faculté de la chimie'",
                "L'université d'État d'Omsk F.M.Dostoevskiy",
                "L'université d'État de Perm, 'la Faculté de la chimie'",
                "L'université russe d'État agraire K.A.Timiryazev, 'la Faculté de la chimie'",
                "L'université russe d'État du pétrole et le gaz I.M.Goubkin, 'la faculté de la chimie'",
                "L'université russe chimique et technologique D.I.Mendeleev",
                "L'université d'État de Rostov, 'la Faculté de la chimie'",
                "L'académie chimique et pharmaceutique de Saint-Pétersbourg",
                "L'université d'État polytechnique de Saint-Pétersbourg, 'la Faculté de la chimie'",
                "L'institut d'État technique de Saint-Pétersbourg (l'Université technique)",
                "L'université d'État technologique des polymères végétaux de Saint-Pétersbourg",
                "L'université d'État de Saint-Pétersbourg 'la Faculté de la chimie'",
                "L'université d'État de Tomsk, 'la Faculté de la chimie'",
                "L'université d'État de Tioumen, l'Institut chimique",
                "L'université d'État pétrolière technique d'Oufa",
                "L'université du sud fédérale, 'la Faculté de la chimie'"
            ],




            "Les Universites Du Sport Et La Culture Physique de la Russie":[
                "L'académie d'État du sport et de la culture physique des Grande Lukes",
                "L'académie d'État de la culture physique de Volgograd",
                "L'institut d'État de la culture physique de Voronej",
                "L'académie d'État de la culture physique d'Extrême Orient",
                "L'institut d'État de la culture physique de Kama",
                "L'université d'État de la culture physique, le sport et le tourisme de Kuban",
                "L'académie d'État de la culture physique de Moscou",
                "L'université nationale scientifique de la culture physique, le sport et la santé",
                "L'académie d'État de la culture physique, le sport et le tourisme de la région de la Volga",
                "L'université russe d'État de la culture physique, le sport, la jeunesse et le tourisme",
                "L'université d'État du sport et de la culture physique",
                "L'université d'État de la culture physique d'Oural",
                "L'institut d'État de la culture physique du Tchaïkovskiy"
            ],



            "Les Universites de La Geologie, L'industrie Miniere Et La Metallurgie de la Russie":[
    "L'université d'État de la Bachkirie, 'la Faculté de la géologie et la géomorphologie'",
    "L'université d'État technologique de Belgorod, 'la Faculté minière'",
    "L'université d'État de Belgorod, 'la faculté minière'",
    "L'Institut des Mines de Vorkuta",
    "L'université d'État de Voronej, 'la Faculté de la géologie'",
    "L'université d'Extrême Orient fédérale, 'la Faculté de la géologie, la géophysique et la géoécologie'",
    "L'université d'État de la Transbaïkalie 'la Faculté de l'industrie minière'",
    "L'université d'État technique d'Irkoutsk, l'Institut de la gestion et le traitement des ressources minérales",
    "L'université d'État d'Irkoutsk, 'la Faculté de la géologie'",
    "L'université de Kazan fédérale, l'Institut de la géologie",
    "L'université d'État de Kuban, 'la Faculté géologique'",
    "L'université d'État technique de Kouzbass, l'Institut des Mines",
    "L'université d'État technique de Lipetsk, l'Institut de la métallurgie",
    "L'université d'État technique de Magnitogorsk, l'Institut de l'industrie minière",
    "L'université d'État minière de Moscou",
    "L'université d'État mécanique de Moscou, 'la Faculté de l'industrie minière'",
    "L'université d'État de Moscou M.V.Lomonosov, 'la Faculté de la géologie'",
    "L'Université nationale minérale et les ressources matières premières 'L'Université minière'",
    "L'université d'État de Novosibirsk, 'la Faculté de la géologie et la géophysique'",
    "L'institut d'État industriel de Norilsk, 'la Faculté minière et technique'",
    "L'université d'État d'Orenbourg, 'la Faculté de la géologie et les ressources minérales'",
    "L'université d'État de Perm, 'la Faculté de la géologie'",
    "L'université d'État de Pétrozavodsk, 'la Faculté minière et géologique'",
    "L'université russe d'État de prospection géologique",
    "L'université russe d'État de la hydrométéorologie",
    "L'Institut d'État des Mines de Saint-Pétersbourg G.V.Plehanov, (l'Université d'État)",
    "L'université d'État de Saint-Pétersbourg, 'la Faculté géologique'",
    "L'université d'État de Saratov, 'la Faculté de la géologie'",
    "L'université d'État de nord-est, 'la Faculté de la géologie et l'industrie minière'",
    "L'université de nord-ouest fédérale M.K.Ammosov, l'Institut des Mines",
    "L'institut d'État métallurgique du Nord du Caucase (l'Université d'État technique)",
    "L'université d'État des géosystèmes et les géotechnologies sibérienne",
    "L'université d'État technique de Tver, 'la Faculté de la géologie appliquée, de la science des mines, d'industrie pétrolière et gazière, et de la géodésie'",
    "L'université d'État de Tomsk, 'la Faculté géologique'",
    "L'université polytechnique de Tomsk, l'Institut des ressources minérales",
    "L'université d'État de Toula, l'Institut de l'industrie minière",
    "L'université d'État minière d'Oural",
    "L'université d'État technique d'Oukhta, l'Institut de la géologie",
    "L'université d'État d'Yugorsk, l'Institut des Mines",
    "L'université d'État du Sud-Ouest, 'la Faculté d'industrie minière'",
    "L'université russe d'État polytechnique du sud M.I.Platov (l'institut polytechnique de Novotcherkassk), 'la Faculté de la géologie, l'industrie minière et d'industrie pétrolière et gazière'",
    "L'université du sud fédérale, l'Institut des sciences terrestres"
],



            "Les Universites Humanitaires Et Les Ecoles Normales Superieures de la Russie":[
                "L'académie d'État d'enseignement d'Altaï",
                "L'université d'État humanitaire et pédagogique d'Amour",
                "L'École normale d'État d'Arzamas A.P.Gaidar",
                "L'académie d'État pédagogique d'Armavir",
                "L'université d'État de l'économie et le droit de Baïkal",
                "L'Université d'État pédagogique de la Bachkirie M.Akmoulla",
                "L'École normale d'État de Blagoveshchensk",
                "L'Université d'État Sociale et Pédagogique de Volgograd",
                "L'académie d'État sociale et humanitaire de Volga",
                "L'Université d'État pédagogique de Vologda",
                "L'Université d'État pédagogique de Voronej",
                "L'université d'État humanitaire de Viatka",
                "L'École normale d'État de Glazov V.G.Korolenko",
                "L'académie d'État pédagogique de la République de Sakha",
                "L'institut russe d'État de la langue A.S.Pouchkin",
                "L'université d'État - le Complexe éducatif, scientifique et industriel",
                "L'Université d'État pédagogique de Daghestan",
                "L'université d'État humanitaire d'Extrême Orient",
                "L'Université d'État Pédagogique d'Elabuga",
                "L'Université d'État linguistique d'Irkoutsk",
                "L'Université d'État pédagogique d'Irkoutsk",
                "L'Université d'État pédagogique de Kalouga K.E.Tsiolkovskiy",
                "L'Université d'État pédagogique de Karatchaïevo-Tcherkessie",
                "L'académie d'État pédagogique de la Carélie",
                "L'École normale supérieure d'État du Komi",
                "L'Université d'État pédagogique de Krasnoïarsk V.P.Astaf'ev",
                "L'académie d'État pédagogique de Kouzbass",
                "L'Université d'État Pédagogique de Lipetsk",
                "L'institut interrégional ouvert social",
                "L'École normale supérieure d'État Mitchourin",
                "L'École normale supérieure d'État de la Mordovie M.E.Evsev'ev",
                "L'université d'État humanitaire et économique de Moscou",
                "L'université d'État humanitaire de Moscou M.A.Cholokhov",
                "L'université d'État linguistique de Moscou",
                "L'université humanitaire de Moscou",
                "L'institut d'enseignement humanitaire et de la technologie informatique de Moscou",
                "L'institut d'enseignement ouvert de Moscou",
                "L'institut des sciences sociales de Moscou",
                "L'institut littéraire de Moscou A.M.Gorkiy",
                "L'Université d'État Pédagogique de Pskov S.V.Kirov",
                "L'université d'État linguistique de Piatigorsk",
                "L'université russe d'État humanitaire",
                "L'Université russe d'État Pédagogique A.I.Gertsen",
                "L'Université d'État Russe professionnelle et pédagogique",
                "L'université russe d'État sociale",
                "L'Université d'État pédagogique de Samara",
                "L'université humanitaire des associations professionnelles de Saint-Pétersbourg",
                "L'institut d'enseignement humanitaire de Saint-Pétersbourg",
                "L'académie humanitaire moderne",
                "L'École normale supérieure d'État de Stavropol",
                "L'École normale supérieure d'État de Taganrog A.P.Tchekhov",
                "L'École normale supérieure d'État musicale de Tambov S.V.Rakhmaninov",
                "L'Université d'État humanitaire et pédagogique tatare",
                "L'académie d'État sociale et pédagogique de Tobolsk D.I.Mendeleev",
                "L'Université d'État pédagogique de Tomsk",
                "L'Université d'État pédagogique d'Oulyanovsk I.N.Oul'yanov",
                "L'Université d'État pédagogique d'Oural",
                "L'École normale supérieure d'État d'Ussuriysk",
                "L'Université d'État pédagogique de Tchéliabinsk",
                "L'École normale supérieure d'État de la Tchétchénie",
                "L'Université d'État Pédagogique de Tchita I.Y.Yakovlev",
                "L'École normale supérieure d'État de Chadrinsk",
                "L'Université d'État Pédagogique d'Iaroslavl K.D.Ouchinskiy"
            ],



    "Les Universites Juridiques de la Russie":[
    "L'institut juridique et économique d'Altaï",
    "L'université d'État de l'économie et le droit de Baïkal",
    "L'institut de l'économie, la gestion et le droit de Kazan",
    "L'université d'État juridique de Moscou O.E.Koutafin",
    "L'institut juridique d'Orel du Ministère de l'Intérieur de la Fédération de Russie",
    "L'académie juridique russe du Ministère de la Justice de la Fédération de Russie",
    "L'académie d'État juridique de Saratov",
    "L'université d'État d'Oural A.M.Gorkiy",
    "L'académie d'État de l'économie et le droit de Khabarovsk"
],


            "Les Universites Petro-Gaziers de la Russie":[
                "L'institut d'État pétrolier d'Almetyevsk",
                "L'université d'État technique d'Arkhangelsk, l'Institut du pétrole et du gaz",
                "L'université d'État technique d'Astrakhan, l'Institut du pétrole et du gaz",
                "L'université d'État technique de Voronej, l'Institut du pétrole et du gaz",
                "L'institut pétrolier de Grozniy l'académicien M.D.Millionchtchikov",
                "L'université d'État technique de Daghestan, l'Institut du pétrole et du gaz",
                "L'université d'Extrême Orient fédérale, l'Institut du pétrole et du gaz",
                "L'université d'État technique d'Irkoutsk, 'la Faculté du pétrole et du gaz'",
                "L'université de Kazan fédérale, l'Institut du pétrole et du gaz",
                "L'institut des technologies humanitaires et d'ingénieur de Kama",
                "L'université d'État technique de Kuban, 'la Faculté du pétrole et du gaz'",
                "L'institut d'État technologique de Maikop, 'la Faculté du pétrole et du gaz'",
                "L'université d'État ouverte de Moscou, l'Institut du pétrole et du gaz",
                "L'institut du business de l'industrie pétrolière et gazière de Moscou",
                "L'université d'État technique d'Omsk, 'la Faculté du pétrole et du gaz'",
                "L'université d'État technique de Perm, 'la Faculté du pétrole et du gaz'",
                "L'université russe d'État du pétrole et du gaz I.M.Goubkine",
                "L'université d'État technique de Samara, 'la Faculté du pétrole et du gaz'",
                "L'Institut d'État des Mines de Saint-Pétersbourg (l'Université Technique), 'la Faculté du pétrole et du gaz'",
                "L'université d'État de Sakhaline, 'la Faculté du pétrole et du gaz'",
                "L'université du nord (Arctique) fédérale M.V.Lomonosov, l'Institut du pétrole et du gaz",
                "L'université d'État technique du Nord du Caucase, l'Institut du pétrole et du gaz",
                "L'institut du pétrole et du gaz de Surgut (l'université d'État de gaz et de pétrole de Tioumen)",
                "L'université d'État de Tomsk, l'Institut du pétrole et du gaz",
                "L'université d'État de gaz et de pétrole de Tioumen",
                "L'université d'État pétrolière technique d'Oufa",
                "L'université d'État technique d'Oukhta, l'Institut du pétrole et du gaz",
                "L'université russe d'État technique du sud, l'Institut du pétrole et du gaz",
                "L'institut de gaz et de pétrole de Yamal (l'université d'État de gaz et de pétrole de Tioumen)"
            ],




            "Les Universites Du Transport Et Des Voies De Communication de la Russie":[
                "L'université d'État des voies de communication d'Extrême Orient",
                "L'université d'État des voies de communication d'Irkoutsk",
                "L'institut des transports ferroviaires de Kourgan (l'université d'État des voies de communication d'Oural)",
                "L'université d'État technique automobile et routière de Moscou",
                "L'université d'État des voies de communication de Moscou",
                "L'université d'État des voies de communication d'Omsk",
                "L'université d'État des voies de communication l'Empereur Alexandre Ier de Saint-Pétersbourg",
                "L'université russe d'État ouverte technique des voies de communication",
                "L'université d'État des voies de communication de Rostov",
                "L'université d'État des voies de communication de Samara",
                "L'institut du nord des voies de communication de Baïkal (l'université d'État des voies de communication d'Irkoutsk)",
                "L'académie d'État automobile et routière sibérienne",
                "L'université d'État des voies de communication sibérienne",
                "L'université d'État des voies de communication d'Oural"
            ],



            "Les Universites De La Technologie D’alimentation de la Russie": [
                "L'Académie d'État de la laiterie de Vologda N.V. Verechtchagin",
                "L'Institut d'État de l'industrie de l'alimentation de Kémérovo",
                "L'Université d'État technologique de Kuban",
                "L'Université d'État de la production alimentaire de Moscou",
                "L'Université d'État des technologies et de la gestion de Moscou K.G. Razoumovskiy",
                "L'Université d'État du froid et des biotechnologies de Saint-Pétersbourg"
            ],


            "Les Universites D’industrie Forestiere Et D’industrie Du Bois de la Russie": [
                "L'Académie d'État de l'économie forestière et des technologies de Voronej",
                "L'Académie d'État polaire (Saint-Pétersbourg)",
                "L'Université d'État de la géodésie et de la cartographie de Moscou",
                "L'Université d'État du bois de Moscou",
                "L'Université d'État technique forestière de Saint-Pétersbourg",
                "L'Université d'État du bois d'Oural"
            ],


            "Les Universites D'état Près Le Gouvernement de la Federation de Russie":[
                "L'Académie du Travail et des Relations Sociales de la Fédération de Russie",
                "L'Académie de la Gestion du Ministère de l'Intérieur de la Fédération de Russie",
                "L'Académie du service d'État de la Gestion de la Bachkirie sous l'égide de la République de Bachkirie",
                "L'Académie diplomatique du Ministère des Affaires étrangères de la Fédération de Russie",
                "L'Institut oriental de la Sibérie du Ministère de l'Intérieur de la Fédération de Russie",
                "L'Institut d'État des Relations internationales de Moscou (Université) du Ministère des Affaires étrangères de la Russie",
                "L'Académie de l'Économie nationale et du Service d'État de Russie",
                "L'Académie d'Oural près du Président de la Fédération de Russie",
                "L'Académie d'État de la Protection civile du Ministère des Situations d'urgence de la Russie",
                "L'Université d'État du Transport par eau de Volga",
                "L'Académie d'État de Volgograd du Ministère de l'Intérieur de la Fédération de Russie",
                "L'Institut de Voronej du Ministère de l'Intérieur de la Fédération de Russie"
            ]
        
            

    },
    fields: {
        "Université Paris-Sorbonne": {
            Licence: ["Lettres", "Histoire", "Philosophie", "Droit"],
            Master: ["Lettres Modernes", "Histoire Contemporaine", "Philosophie Politique", "Droit International"],
            Doctorat: ["Recherche en Lettres", "Histoire des Civilisations", "Philosophie Avancée", "Droit Comparé"]
        },
        "École Polytechnique": {
            Licence: ["Mathématiques", "Physique", "Informatique", "Génie Civil"],
            Master: ["Mathématiques Appliquées", "Physique Quantique", "Intelligence Artificielle", "Génie Mécanique"],
            Doctorat: ["Recherche en Mathématiques", "Physique Théorique", "Systèmes Informatiques", "Structures Avancées"]
        },
        "Université de Montréal": {
            Licence: ["Médecine", "Informatique", "Psychologie", "Économie"],
            Master: ["Médecine Avancée", "Science des Données", "Psychologie Clinique", "Économie Internationale"],
            Doctorat: ["Recherche Médicale", "Informatique Théorique", "Psychologie Cognitive", "Économie Quantitative"]
        },
        "Université Technique d'État de Tambov": {
            Licence: ["Architecture", "Informatique", "Génie Mécanique", "Économie"],
            Master: ["Architecture Avancée", "Systèmes Informatiques", "Génie Industriel", "Gestion Financière"],
            Doctorat: ["Recherche en Architecture", "Informatique Avancée", "Génie Mécanique Avancé", "Économie Appliquée"]
        },
        "Université d'État de Moscou": {
            Licence: ["Médecine", "Physique", "Mathématiques", "Droit"],
            Master: ["Médecine Générale", "Physique Appliquée", "Mathématiques Avancées", "Droit International"],
            Doctorat: ["Recherche Médicale", "Physique Théorique", "Mathématiques Pures", "Droit Comparé"]
        },
        // Ajoutez d'autres universités et leurs niveaux ici
    },
    accommodations: [
        { type: "Chambre Simple", capacity: "1 personne", price: 150000 },
        { type: "Chambre Double", capacity: "2 personnes", price: 100000 },
        { type: "Studio", capacity: "1 personne", price: 250000 },
        { type: "Appartement T1", capacity: "1-2 personnes", price: 350000 },
        { type: "Appartement T2", capacity: "2-3 personnes", price: 450000 },
        { type: "Résidence Universitaire", capacity: "1 personne", price: 80000 }
    ],
    additionalServices: [
        {
            id: "passport",
            name: "Passeport",
            description: "Aide à l'obtention d'un passeport",
            price: 50000
        },
        {
            id: "translation",
            name: "Traduction",
            description: "Traduction de vos certificats et diplômes",
            price: 30000
        },
        {
            id: "airport",
            name: "Accueil à l'aéroport",
            description: "Service d'accueil et suivi à l'aéroport",
            price: 300000
        }
    ],
    studyLevels: ["Licence", "Master", "Doctorat"]
};

